name: "OpenDataTourism.ch"
description: "Gemeinsam an offen Daten für den Tourismus arbeiten, zur Verfügungstellen und ohne Einschränkunen weiterverwenden."
url: "opendatatourism.ch"
show_downloads: false
theme: jekyll-theme-cayman
github: false
is_project_page: false