name: "OpenDataTourism.ch"
description: "Gemeinsam an offen Daten zu arbeiten, zur Verfügung stellen und ohne Einschränkunen weiterverwenden."
url: "opendatatourism.ch"
show_downloads: false
theme: jekyll-theme-cayman
github: false
is_project_page: false